language: node_js
node_js:
  - '0.10'
addons:
  firefox: "17.0"
before_script:
  - npm install -g bower grunt-cli
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
services: mongodb
after_script: 
  - ./node_modules/karma/bin/karma start
  - istanbul cover ./node_modules/mocha/bin/_mocha server/api/**/*.spec.js
  - cat ./coverage/lcov.info ./coverage/karma/**/*.info > lcov.info 
  - node node_modules/lcov-filter/index.js lcov.info config | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage